version: '3.8'
services:
  listener:
    image: docker.io/mendhak/http-https-echo:31
    container_name: listener
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - apim_default

networks:
  apim_default:
    external: true


  # wso2am:
  #   build: .
  #   container_name: wso2am
  #   healthcheck:
  #     test: ["CMD", "nc", "-z","localhost", "9443"]
  #     interval: 10s
  #     start_period: 180s
  #     retries: 20
  #   volumes:
  #     - ./conf/deployment.toml:/home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
  #     - ./conf/log4j2.properties:/home/wso2carbon/wso2-config-volume/repository/conf/log4j2.properties
  #     #- ./conf/site.json:/home/wso2carbon/wso2am-4.2.0/repository/deployment/server/jaggeryapps/publisher/site/conf/site.json
  #     - /var/log/docker:/home/wso2carbon/wso2am-4.2.0/repository/logs
  #     - ./dropins/org.wso2.carbon.healthcheck.api.core-1.3.1.jar:/home/wso2carbon/wso2am-4.2.0/repository/components/dropins/org.wso2.carbon.healthcheck.api.core-1.3.1.jar
  #     - ./webapps/api#health-check#v1.0.war:/home/wso2carbon/wso2am-4.2.0/repository/deployment/server/webapps/api#health-check#v1.0.war
  #     - ./conf/health-check-config.xml:/home/wso2carbon/wso2-config-volume/repository/conf/health-check-config.xml
  #   ports:
  #     - "9443:9443"
  #     - "8280:8280"
  #     - "8243:8243"