version: '3.8'
services:
  listener:
    image: docker.io/mendhak/http-https-echo:31
    container_name: listener
    ports:
      - "8080:8080"
      - "8443:8443"
#     networks:
#       - apim_default

# networks:
#   apim_default:
#     external: true


  wso2am:
    build: .
    container_name: wso2am
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/api/health-check/v1.0/health"]
      interval: 10s
      start_period: 180s
      retries: 20
    volumes:
      - ./conf/deployment.toml:/home/wso2carbon/wso2-config-volume/repository/conf/deployment.toml
      - ./conf/log4j2.properties:/home/wso2carbon/wso2-config-volume/repository/conf/log4j2.properties
      - /var/log/docker:/home/wso2carbon/wso2am-4.2.0/repository/logs
      - ./dropins/org.wso2.carbon.healthcheck.api.core-1.3.1.jar:/home/wso2carbon/wso2am-4.2.0/repository/components/dropins/org.wso2.carbon.healthcheck.api.core-1.3.1.jar
      - ./webapps/api#health-check#v1.0.war:/home/wso2carbon/wso2am-4.2.0/repository/deployment/server/webapps/api#health-check#v1.0.war
      - ./conf/health-check-config.xml:/home/wso2carbon/wso2-config-volume/repository/conf/health-check-config.xml
      - ./postgresql/postgresql-42.7.4.jar:/home/wso2carbon/wso2-artifact-volume/repository/components/lib/postgresql-42.7.4.jar
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=apim_db
      - DB_USER=apimadmin
      - DB_PASSWORD=apimadmin

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./postgresql/postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
      - ./postgresql/apimgt/postgresql.sql:/docker-entrypoint-initdb.d/apimgt/postgresql.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
